name: nba_top_shot_insights
description: Get notified about market events straight out of the blockchain
version: 0.1.0


environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
